# app
app:
  host: 0.0.0.0
  port: 8080
{% if not without_postgres %}
# postgres
postgres:
  user: postgres
  password: postgres
  database: postgres
  port: 5432
  host: postgres
{% endif %}{% if redis %}
# redis
redis:
  port: 6379
  host: redis
{% endif %}