# app
app:
  host: 0.0.0.0
  port: 9000
{% if not without_postgres %}
# postgres
postgres:
  user: postgres_test
  password: postgres_test
  database: postgres_test
  port: 5432
  host: postgres
{% endif %}{% if redis %}
# redis
redis:
  port: 6379
  host: redis
{% endif %}